# Introduction to Numpy

In [1]:
!pip install numpy

## Importing numpy


In [3]:
import numpy as np

In [5]:
even =[6,8,6,4,12,14]
len(even)

6

In [6]:
evenArray = np.array(even)    #changing list to array
evenArray

array([ 6,  8,  6,  4, 12, 14])

In [7]:
evenArray[0]

6

In [8]:
evenArray[1]

8

In [9]:
evenArray[5]

14

In [10]:
evenArray[-1]    #negative indexing in array

14

In [11]:
evenArray[-3]

4

###  Slicing in python

In [12]:
evenArray[1:4]   #slices the values from 1 to 3  [1,4).

array([8, 6, 4])

In [13]:
type(evenArray)    #returns the type of the evenArray

numpy.ndarray

In [15]:
evenArray.ndim #returns the dimension of the array.

1

## Difference between List and array 
> - Numpy array are faster than python list.
> - Numpy array are memory effecient than python list.
> - Numpy array supports homogeneous date type while python list supports multiple data type.

In [16]:
x = np.zeros(5,dtype=np.int8)  #Numpy array are memory effecient than python list.

array([0, 0, 0, 0, 0], dtype=int8)

In [17]:
np.ones(3,dtype=np.float16)

array([1., 1., 1.], dtype=float16)

In [21]:
np.random.randint(0,10) #non deterministic

3

In [22]:
np.random.seed(0) #deterministic 
np.random.randint(0,10)

5

In [37]:
np.random.seed(2023)                   #random numbers of size 50000 in range 1 to 10
x = np.random.randint(1,10,size=50000)

In [38]:
xList = x.tolist()                #changes array to list  , typecasting

In [39]:
a =[8,9,7]
sq=[]
for item in a:
    sq.append(item ** 2)

In [40]:
sq

[64, 81, 49]

- ### List comprehension

In [41]:
sq = [item**2 for item in a]

In [42]:
%%time
sq=[item **2 for item in xList]

CPU times: user 5.77 ms, sys: 280 µs, total: 6.05 ms
Wall time: 5.93 ms


In [45]:
%%time
#time it function , times the execution time
sq = x ** 2

CPU times: user 109 µs, sys: 20 µs, total: 129 µs
Wall time: 134 µs


## .linspace()
- create a linear spacing in a given range of the provided number

In [47]:
np.linspace(0,1,5)   #creates 5 elements of equal spacing between 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [48]:
np.arange(11,24,1)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [49]:
# Start 11
# Stop 24
# Step 1

In [50]:
x = np.array([4,9])
y = np.array([2,3])

In [53]:
x + y    #Element wise addition because x and y are array / vector addition

array([ 6, 12])

In [54]:
x / y

array([2., 3.])

In [55]:
x % y

array([0, 0])

In [56]:
x * y

array([ 8, 27])

## Statistics

In [62]:
np.random.seed(0)
x = np.random.randint(1,20,size=40)

In [63]:
x

array([13, 16,  1,  4,  4,  8, 10, 19,  5,  7, 13,  2,  7,  8, 15, 18,  6,
       14,  9, 10, 17,  6, 16, 16,  1, 19,  4, 18, 15,  8,  1,  2, 10,  1,
       11,  4, 12, 19,  3,  1])

In [64]:
np.mean(x)

9.325

In [65]:
np.median(x)

8.5

In [66]:
from scipy.stats import mode
mode(x)

ModeResult(mode=1, count=5)

In [67]:
np.std(x)  # standard deviation

5.943010600697259

In [68]:
np.var(x) #variance

35.319375

# 2d array

In [69]:
matrix = np.array([ [1,2,3] , [4,5,6] , [7,8,9] ])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
matrix.ndim

2

In [71]:
matrix[1,2]

6

In [72]:
matrix[2,1]

8

In [74]:
matrix[1:,1:]

array([[5, 6],
       [8, 9]])

In [78]:
matrix[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

### dot product / Matrix multiplication

In [81]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])

In [82]:
A.shape

(2, 3)

In [83]:
B.shape

(3, 2)

In [84]:
output = np.dot(A,B)

In [85]:
output

array([[ 58,  64],
       [139, 154]])

In [87]:
det = np.linalg.det(output)   #finding determinant of output

In [88]:
det

36.00000000000032

In [91]:
np.round(det,2)

36.0

In [92]:
np.linalg.inv(output)   #finding inverse of the output

array([[ 4.27777778, -1.77777778],
       [-3.86111111,  1.61111111]])

### Converting 2d array to 1d array

In [94]:
x = np.array([[4,5,6],[3,2,0]])
print(x)
print (f"dimension = {x.ndim}")

[[4 5 6]
 [3 2 0]]
dimension = 2


In [96]:
xOneDim = x.flatten()
print(xOneDim)
print(f"dimension = {xOneDim.ndim}")

[4 5 6 3 2 0]
dimension = 1


### Converting 1d array to 2d array / .reshape()

In [99]:
x = np.arange(1,10)
x.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
x.reshape(1,-1) 
# no of rows= 1,
#no of column unknown
#row matrix

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [103]:
x.reshape(-1,1)
# no of columns= 1,
# no of row unknown
# column matrix

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [104]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
x.sum()   #sum of all the elements

21

In [107]:
x.sum(axis=1)  
#horizontal operation

array([ 6, 15])

In [109]:
x.sum(axis=0)
#vertical operation

array([5, 7, 9])

### Broadcasting


In [110]:
x = np.array([2,5])

In [114]:
x

array([2, 5])

In [115]:
x * 5

array([10, 25])

In [116]:
x + 8

array([10, 13])